In [22]:
# ignore this
.libPaths(c("/net/home/swolf/R/x86_64-pc-linux-gnu-library/4.4", .libPaths()))

In [ ]:
library(data.table) 
dtn = 10
setDTthreads(threads = dtn) #defines how many threads data.table is allowed to use

In [ ]:
gbif_try_glonaf <- fread("/net/scratch/swolf/GBIF/GBIF_try6_GloNAF_WCVP_status_woodiness_CS.csv")
head(gbif_try_glonaf)

  gbifID    speciesKey decimalLatitude decimalLongitude h3_res3
1 891018389 2986175    37.81738        -122.0341        832830fffffffff
2 891018395 2878586    37.93479        -122.1528        832830fffffffff
3 891018399 2928026    37.16354        -121.4834        832834fffffffff
4 891018400 3039404    37.89495        -121.9295        832830fffffffff
5 891018401 2878384    37.88037        -121.9101        832830fffffffff
6 891018402 5298502    38.58038        -123.3133        832831fffffffff
  h3_res4         X.X3117.  X.X14.    X.X50.    X.X146.  ⋯ X.X351.  X.X6.
1 842830dffffffff 14.198018 22.394893 1.8711526 19.09068 ⋯ 2.054130 0.4096437
2 8428309ffffffff  9.527582 18.021850 1.8542082 25.20681 ⋯ 2.204626 2.7929593
3 8428345ffffffff 12.834863  9.708971 0.8664297       NA ⋯ 1.147330        NA
4 842830dffffffff  4.307864 14.872387 3.4717732 30.36493 ⋯ 1.588747 3.6377510
5 842830dffffffff  7.470983 14.708481 1.9751395 30.55207 ⋯ 1.711807 4.1715545
6 8428311ffffffff 12.687887 17.383079 1.5956363 32.10343 ⋯ 1.025867 0.3838454
  X.X95.   X.X138.   X.X1080.  X.X78.    X.X4.     most_common_pft
1 90.06101 139.73576 1774.1975 -3.088086 0.7170612 Shrub
2 75.85665  86.86699  235.6233 -2.107607 0.5244097 Tree
3 97.96611        NA 6980.9510        NA 0.5196287 Grass
4 79.49740 104.98971  265.6407 -2.293326 0.6810611 Shrub
5 87.50078  36.89623  513.2988 -2.704216 0.7399179 Tree
6 81.96427 190.18055 3880.6637  1.950235 0.3792678 Grass
  majority_status woodiness
1 native          woody
2 native          woody
3 native          non-woody
4 native          woody
5 native          woody
6 native          non-woody

In [ ]:
head(gbif_try_glonaf)

  gbifID    speciesKey decimalLatitude decimalLongitude h3_res3
1 891018389 2986175    37.81738        -122.0341        832830fffffffff
2 891018395 2878586    37.93479        -122.1528        832830fffffffff
3 891018399 2928026    37.16354        -121.4834        832834fffffffff
4 891018400 3039404    37.89495        -121.9295        832830fffffffff
5 891018401 2878384    37.88037        -121.9101        832830fffffffff
6 891018402 5298502    38.58038        -123.3133        832831fffffffff
  h3_res4         X.X3117.  X.X14.    X.X50.    X.X146.  ⋯ X.X351.  X.X6.
1 842830dffffffff 14.198018 22.394893 1.8711526 19.09068 ⋯ 2.054130 0.4096437
2 8428309ffffffff  9.527582 18.021850 1.8542082 25.20681 ⋯ 2.204626 2.7929593
3 8428345ffffffff 12.834863  9.708971 0.8664297       NA ⋯ 1.147330        NA
4 842830dffffffff  4.307864 14.872387 3.4717732 30.36493 ⋯ 1.588747 3.6377510
5 842830dffffffff  7.470983 14.708481 1.9751395 30.55207 ⋯ 1.711807 4.1715545
6 8428311ffffffff 12.687887 17.383079 1.5956363 32.10343 ⋯ 1.025867 0.3838454
  X.X95.   X.X138.   X.X1080.  X.X78.    X.X4.     most_common_pft
1 90.06101 139.73576 1774.1975 -3.088086 0.7170612 Shrub
2 75.85665  86.86699  235.6233 -2.107607 0.5244097 Tree
3 97.96611        NA 6980.9510        NA 0.5196287 Grass
4 79.49740 104.98971  265.6407 -2.293326 0.6810611 Shrub
5 87.50078  36.89623  513.2988 -2.704216 0.7399179 Tree
6 81.96427 190.18055 3880.6637  1.950235 0.3792678 Grass
  majority_status woodiness
1 native          woody
2 native          woody
3 native          non-woody
4 native          woody
5 native          woody
6 native          non-woody

### Add biome

In [ ]:
# read /net/scratch/swolf/GBIF/gbif_res3_try6_CS_wcvp_summary_stats_inkl_pca_mean_group_region_log10.csv
regions <- fread("/net/scratch/swolf/GBIF/gbif_res3_try6_CS_wcvp_summary_stats_inkl_pca_mean_group_region_log10.csv")

In [ ]:
head(regions)

  h3_res3         group  PC1       PC2        PC3         PC4         count
1 832830fffffffff all    -1.803834  0.9603752 -0.05605286  0.28704004 534527
2 832830fffffffff native -1.354830  0.1581176 -0.61312183  0.47782598 378645
3 832834fffffffff all    -1.781438  0.5006442 -0.16618360  0.48394999 449715
4 832834fffffffff native -1.299022 -0.2982885 -0.69903004  0.65921448 334995
5 832831fffffffff all    -1.976354  0.9112940 -0.61732579 -0.06457907  64487
6 832831fffffffff native -1.591604  0.3624014 -1.12528671  0.03630553  51697
  X.X3117. X.X14. X.X50. ⋯ X.X237. X.X614. X.X351. X.X6.  X.X95. X.X138.
1 18.214   22.920 1.517  ⋯ 0.523   3.564   0.076   -0.419 89.707 2.436
2 16.342   21.572 1.552  ⋯ 0.542   3.533   0.095   -0.376 88.577 2.376
3 17.946   22.496 1.543  ⋯ 0.532   3.556   0.075   -0.395 89.730 2.458
4 15.877   21.214 1.582  ⋯ 0.556   3.531   0.091   -0.339 88.691 2.388
5 18.615   21.891 1.429  ⋯ 0.528   3.573   0.073   -0.409 89.313 2.452
6 17.566   20.829 1.440  ⋯ 0.553   3.543   0.085   -0.383 88.553 2.387
  X.X1080. X.X78. X.X4. region
1 3.418    -0.386 0.442 12_NA
2 3.351    -0.861 0.471 12_NA
3 3.400    -0.478 0.453 5_NA
4 3.324    -0.897 0.478 5_NA
5 3.388    -0.634 0.442
6 3.333    -1.049 0.460

In [ ]:
# filter regions for columns "region", "h3_res3"
regions <- regions[, .(region, h3_res3)]

In [ ]:
# remove duplicate rows in regions
regions <- unique(regions)
dim(regions)

[1] 9752    2

In [ ]:
# add "region" column from regions with gbif_try_glonafon "h3_res3" column -left join
gbif_try_glonaf_region <- merge(gbif_try_glonaf, regions[, .(h3_res3, region)], by.x = "h3_res3", by.y = "h3_res3", all.x = TRUE)
head(gbif_try_glonaf_region)

  h3_res3         gbifID     speciesKey decimalLatitude decimalLongitude
1 83001afffffffff 2868098768 5373235    80.86896        60.11601
2 83001afffffffff 2868244889 5373235    80.56499        58.77470
3 83001afffffffff 2963791473 3032869    80.86925        60.11534
4 83001afffffffff 2963827476 3032796    80.86892        60.11567
5 83001afffffffff 2963828464 8348125    80.57980        58.78011
6 83001afffffffff 2963894480 3032869    80.87010        60.12231
  h3_res4         X.X3117. X.X14.   X.X50.    X.X146.  ⋯ X.X6.     X.X95.
1 84001a7ffffffff 26.34396 31.80986 1.3023890 14.07958 ⋯ 0.1420849 81.86211
2 84001a5ffffffff 26.34396 31.80986 1.3023890 14.07958 ⋯ 0.1420849 81.86211
3 84001a7ffffffff 22.99855 18.34218 0.7947765 22.47771 ⋯ 0.3336128       NA
4 84001a7ffffffff 14.68447 17.52737 1.3003913 27.04418 ⋯ 0.1397860 89.27051
5 84001a5ffffffff 13.85801 29.06491 2.2053008 18.02487 ⋯ 0.1539388 94.89751
6 84001a7ffffffff 22.99855 18.34218 0.7947765 22.47771 ⋯ 0.3336128       NA
  X.X138.   X.X1080.  X.X78.     X.X4.     most_common_pft majority_status
1  147.6106  995.2516  0.8064726 0.3427519 Grass           native
2  147.6106  995.2516  0.8064726 0.3427519 Grass           native
3  121.8376 1191.1562 -0.8273339 0.2672617 Grass           native
4  171.7318 1286.0739 -0.3425649 0.3335554 Grass           native
5 1390.6491 7342.5624 -0.2820277 0.4954349 Grass
6  121.8376 1191.1562 -0.8273339 0.2672617 Grass           native
  woodiness region
1 non-woody 11_PA
2 non-woody 11_PA
3 non-woody 11_PA
4           11_PA
5 non-woody 11_PA
6 non-woody 11_PA

In [ ]:
# split "region" column into realm and biome with "_" as separator
gbif_try_glonaf_region[, c("biome", "realm") := tstrsplit(region, "_", fixed = TRUE)]
head(gbif_try_glonaf_region)

  h3_res3         gbifID     speciesKey decimalLatitude decimalLongitude
1 83001afffffffff 2868098768 5373235    80.86896        60.11601
2 83001afffffffff 2868244889 5373235    80.56499        58.77470
3 83001afffffffff 2963791473 3032869    80.86925        60.11534
4 83001afffffffff 2963827476 3032796    80.86892        60.11567
5 83001afffffffff 2963828464 8348125    80.57980        58.78011
6 83001afffffffff 2963894480 3032869    80.87010        60.12231
  h3_res4         X.X3117. X.X14.   X.X50.    X.X146.  ⋯ X.X138.   X.X1080.
1 84001a7ffffffff 26.34396 31.80986 1.3023890 14.07958 ⋯  147.6106  995.2516
2 84001a5ffffffff 26.34396 31.80986 1.3023890 14.07958 ⋯  147.6106  995.2516
3 84001a7ffffffff 22.99855 18.34218 0.7947765 22.47771 ⋯  121.8376 1191.1562
4 84001a7ffffffff 14.68447 17.52737 1.3003913 27.04418 ⋯  171.7318 1286.0739
5 84001a5ffffffff 13.85801 29.06491 2.2053008 18.02487 ⋯ 1390.6491 7342.5624
6 84001a7ffffffff 22.99855 18.34218 0.7947765 22.47771 ⋯  121.8376 1191.1562
  X.X78.     X.X4.     most_common_pft majority_status woodiness region biome
1  0.8064726 0.3427519 Grass           native          non-woody 11_PA  11
2  0.8064726 0.3427519 Grass           native          non-woody 11_PA  11
3 -0.8273339 0.2672617 Grass           native          non-woody 11_PA  11
4 -0.3425649 0.3335554 Grass           native                    11_PA  11
5 -0.2820277 0.4954349 Grass                           non-woody 11_PA  11
6 -0.8273339 0.2672617 Grass           native          non-woody 11_PA  11
  realm
1 PA
2 PA
3 PA
4 PA
5 PA
6 PA

## Most common introduced species

In [ ]:
# get most common speciesKey with counts for native and non-native statuses
most_common_species <- gbif_try_glonaf_region[, .(
  total_count = .N,
  native_count = sum(majority_status == "native", na.rm = TRUE),
  non_native_count = sum(majority_status == "non-native", na.rm = TRUE)
), by = .(speciesKey, realm)][order(-non_native_count)]
head(most_common_species, 10)

   speciesKey realm total_count native_count non_native_count
1  2891770    PA    124840        71         124725
2  2891782    PA     85680       393          85274
3  3021496    PA     89193      5031          83287
4  2928226    PA     81751       112          81637
5  5376075    NA     72935        41          72894
6  3109086    PA     67002         2          67000
7  3171949    NA     63908        13          63895
8  5358748    NA     61510         0          61510
9  3054368    PA     61839      1168          60669
10 2926557    NA     60187         6          60181

In [ ]:
# get top 10 most common non-native species for each realm
top_non_native_species_by_realm <- gbif_try_glonaf_region[majority_status == "non-native", .N, by = .(speciesKey, realm)][order(-N), head(.SD, 10), by = realm]
head(top_non_native_species_by_realm, 20)

   realm speciesKey N
1  PA    2891770    124725
2  PA    2891782     85274
3  PA    3021496     83287
4  PA    2928226     81637
5  PA    3109086     67000
6  PA    3054368     60669
7  PA    3172077     60161
8  PA    8677924     56205
9  PA    3003979     55185
10 PA    2889173     50489
11 NA    5376075     72894
12 NA    3171949     63895
13 NA    5358748     61510
14 NA    2926557     60181
15 NA    8324121     48807
16 NA    3034742     47901
17 NA    3003244     45301
18 NA    2926682     42393
19 NA    3039491     41446
20 NA    5392252     39810

In [ ]:
# save top_non_native_species_by_realm to csv
fwrite(top_non_native_species_by_realm, "/net/scratch/swolf/GBIF/top_non_native_species_by_realm.csv")

In [ ]:
#save most_common_species as csv
fwrite(most_common_species, "/net/scratch/swolf/GBIF/most_common_introduced_species.csv")

In [ ]:
TxR_glonaf <- fread("../Data/GloNAF2/glonaf_TxR_tax_harmony.csv")

setnames(TxR_glonaf, "GBIFKeyGBIF", "speciesKey")
head(TxR_glonaf)#

  taxa_accepted                      speciesKey wcvp12_accepted_plant_name_id
1 Abelia chinensis                   5599251    2609453
2 Abelia grandiflora                 5599251    2609470
3 Abelmoschus esculentus             3152707    2609574
4 Abelmoschus ficulneus              3940858    2609577
5 Abelmoschus manihot                3152706    2609589
6 Abelmoschus manihot subsp. manihot 7279656    3261487
  ABW AFG AGO AIA ALB AND ARE ⋯ WSM.NUE YEM ZAF ZMB ZWE.C ZWE.E ZWE.N ZWE.S
1 0   0   0   0   0   0   0   ⋯ 0       0   0   0   0     0     0     0
2 0   0   0   0   0   0   0   ⋯ 0       0   0   0   0     0     0     0
3 0   0   0   1   0   0   0   ⋯ 0       0   1   0   0     0     0     0
4 0   0   0   0   0   0   0   ⋯ 0       0   0   0   0     0     0     0
5 0   0   0   0   0   0   0   ⋯ 0       0   0   0   0     0     0     0
6 0   0   0   0   0   0   0   ⋯ 0       0   0   0   0     0     0     0
  ZWE.W frequency
1 0      3
2 0     11
3 0     54
4 0      9
5 0     11
6 0      4

In [ ]:
# merge top_non_native_species_by_realm
TxR_glonaf <- TxR_glonaf[, .(taxa_accepted, speciesKey)]
top_non_native_species_by_realm <- merge(TxR_glonaf, top_non_native_species_by_realm, by = "speciesKey")

In [ ]:
top_non_native_species_by_realm

   speciesKey taxa_accepted                            realm N
1  2706164    Holcus lanatus                           AA      2705
2  2735117    Cocos nucifera                           NT      2694
3  2735117    Cocos nucifera                           OC       428
4  2758700    Hedychium gardnerianum                   OC       497
5  2765156    Tradescantia fluminensis                 AA      2496
6  2874484    Carica papaya                            NT      2020
7  2874581    Momordica charantia                      NT      3013
8  2889173    Reynoutria japonica                      PA     50489
9  2891661    Oxalis pes-caprae                        NA     16446
10 2891707    Oxalis debilis                           IM      4148
11 2891770    Impatiens glandulifera                   PA    124725
12 2891782    Impatiens parviflora                     PA     85274
13 2891930    Casuarina equisetifolia                  OC       518
14 2925303    Lantana camara                           IM      4685
15 2925303    Lantana camara                           AT      3693
16 2925303    Lantana camara                           OC       397
17 2925895    Echium plantagineum                      AT      2118
18 2926557    Glechoma hederacea                       NA     60181
19 2926682    Lamium purpureum                         NA     42393
20 2928226    Phacelia tanacetifolia                   PA     81637
21 2931469    Solanum mauritianum                      AT      3572
22 2931469    Solanum mauritianum                      AA      2368
23 2951984    Ulex europaeus                           AA      2856
24 2969284    Mimosa pudica                            IM      6022
25 2969284    Mimosa pudica                            OC       351
26 2970418    Leucaena leucocephala                    IM      3552
27 2970418    Leucaena leucocephala                    OC       646
28 2978552    Acacia saligna                           AT      4144
29 2979775    Acacia mearnsii                          AT      4608
30 3003979    Rosa rugosa                              PA     55185
⋮  ⋮          ⋮                                        ⋮     ⋮
51  3172077   Veronica persica                         NA    15504
52  3172574   Spathodea campanulata                    OC      382
53  3172574   Spathodea campanulata subsp. campanulata OC      382
54  3189870   Acer pseudoplatanus                      NA    13959
55  3190653   Ailanthus altissima                      NA    12912
56  3190653   Ailanthus altissima var. sutchuenensis   NA    12912
57  5339879   Morinda citrifolia                       OC     1022
58  5341297   Prunella vulgaris                        AA     2510
59  5358748   Trifolium repens                         NA    61510
60  5358748   Trifolium repens                         NT     3813
61  5358748   Trifolium repens                         AA     3292
62  5376075   Alliaria petiolata                       NA    72894
63  5376075   Alliaria petiolata                       NA    17991
64  5380041   Ricinus communis                         NA    12002
65  5380041   Ricinus communis                         NT     7306
66  5380041   Ricinus communis                         AT     2280
67  5384064   Opuntia megacantha                       AT     2950
68  5392252   Cichorium intybus                        NA    39810
69  5398421   Mikania micrantha                        IM     4935
70  5415463   Thunbergia alata                         NT     6373
71  5420641   Psidium cattleyanum                      OC      384
72  5914287   Melia azedarach                          AT     2552
73  7883492   Hedychium coronarium                     NT     2561
74  8184903   Lysimachia arvensis                      AA     2758
75  8208358   Plantago lanceolata                      AT     3314
76  8208358   Plantago lanceolata                      AA     3527
77  8324121   Trifolium pratense                       NA    48807
78  8677924   Pittosporum tobira                       PA    56205
79  8677924   Pittosporum tobira                       NA    42288
80 11015824   Heliotropium arboreum                    OC      482

In [ ]:
# filter realms for PA, NA, AA, NT, IM, AT
top_non_native_species_by_realm <- top_non_native_species_by_realm[realm %in% c("PA", "NA", "AA", "NT", "IM", "AT")]

In [ ]:
# sort by realm
top_non_native_species_by_realm <- top_non_native_species_by_realm[order(realm, N)]
top_non_native_species_by_realm

   speciesKey taxa_accepted            realm N
1  2931469    Solanum mauritianum      AA      2368
2  2765156    Tradescantia fluminensis AA      2496
3  5341297    Prunella vulgaris        AA      2510
4  2706164    Holcus lanatus           AA      2705
5  8184903    Lysimachia arvensis      AA      2758
6  2951984    Ulex europaeus           AA      2856
7  5358748    Trifolium repens         AA      3292
8  8208358    Plantago lanceolata      AA      3527
9  3114986    Arctotheca calendula     AA      3964
10 3112801    Cirsium vulgare          AA      4458
11 2925895    Echium plantagineum      AT      2118
12 5380041    Ricinus communis         AT      2280
13 5914287    Melia azedarach          AT      2552
14 5384064    Opuntia megacantha       AT      2950
15 8208358    Plantago lanceolata      AT      3314
16 2931469    Solanum mauritianum      AT      3572
17 2925303    Lantana camara           AT      3693
18 2978552    Acacia saligna           AT      4144
19 2979775    Acacia mearnsii          AT      4608
20 2970418    Leucaena leucocephala    IM      3552
21 3087725    Chromolaena odorata      IM      3658
22 3169830    Catharanthus roseus      IM      3718
23 3086784    Parthenium hysterophorus IM      3947
24 2891707    Oxalis debilis           IM      4148
25 3068937    Euphorbia hirta          IM      4336
26 2925303    Lantana camara           IM      4685
27 5398421    Mikania micrantha        IM      4935
28 2969284    Mimosa pudica            IM      6022
29 3149462    Tridax procumbens        IM      6806
30 5392252    Cichorium intybus        NA     39810
31 3039491    Rhamnus cathartica       NA     41446
32 2926682    Lamium purpureum         NA     42393
33 3034742    Daucus carota            NA     47901
34 3034742    Daucus glaber            NA     47901
35 8324121    Trifolium pratense       NA     48807
36 2926557    Glechoma hederacea       NA     60181
37 5358748    Trifolium repens         NA     61510
38 3171949    Verbascum thapsus        NA     63895
39 5376075    Alliaria petiolata       NA     72894
40 2874484    Carica papaya            NT      2020
41 3084719    Portulaca oleracea       NT      2344
42 3168943    Hippobroma longiflora    NT      2382
43 7883492    Hedychium coronarium     NT      2561
44 2735117    Cocos nucifera           NT      2694
45 2874581    Momordica charantia      NT      3013
46 5358748    Trifolium repens         NT      3813
47 5415463    Thunbergia alata         NT      6373
48 5380041    Ricinus communis         NT      7306
49 2889173    Reynoutria japonica      PA     50489
50 3003979    Rosa rugosa              PA     55185
51 8677924    Pittosporum tobira       PA     56205
52 3172077    Veronica persica         PA     60161
53 3054368    Juglans regia            PA     60669
54 3109086    Senecio inaequidens      PA     67000
55 2928226    Phacelia tanacetifolia   PA     81637
56 3021496    Prunus laurocerasus      PA     83287
57 2891782    Impatiens parviflora     PA     85274
58 2891770    Impatiens glandulifera   PA    124725

In [ ]:
# print non-unique taxa_accepted in top_non_native_species_by_realm
top_non_native_species_by_realm[duplicated(taxa_accepted) | duplicated(taxa_accepted, fromLast = TRUE), taxa_accepted]

 [1] "Solanum mauritianum" "Trifolium repens"    "Plantago lanceolata"
 [4] "Ricinus communis"    "Plantago lanceolata" "Solanum mauritianum"
 [7] "Lantana camara"      "Lantana camara"      "Trifolium repens"
[10] "Trifolium repens"    "Ricinus communis"

In [ ]:
# most common non-native species per realm
top_non_native_species_by_realm[,.SD[which.max(N)], by = realm]

  realm speciesKey taxa_accepted          N
1 AA    3112801    Cirsium vulgare          4458
2 AT    2979775    Acacia mearnsii          4608
3 IM    3149462    Tridax procumbens        6806
4 NA    5376075    Alliaria petiolata      72894
5 NT    5380041    Ricinus communis         7306
6 PA    2891770    Impatiens glandulifera 124725